### ISSUE TITLE
make check => cannot find -lsubunit

### ISSUE THREAD

**Issue by tseemann** [sanger-pathogens/snp_sites#33]
```
% make check

<snip>
/usr/bin/ld: cannot find -lsubunit
collect2: error: ld returned 1 exit status
make[2]: *** [run-all-tests] Error 1
```

**Comment by tillea** [comment]
On a Debian (derived) system just install libsubunit-dev.  If you are trying to build a Debian package add this to the Build-Depends.

How to gather this knowledge

   apt-file search libsubunit

will tell you in what package the missing library can be found.

Kind regards

       Andreas.

**Comment by andrewjpage** [comment]
i've removed subunit temporarily since it breaks on osx and older versions of ubuntu. I'll have to think about this one.
