### ISSUE TITLE
possible to convert to redhat?

### ISSUE THREAD

**Issue by ntchuang** [sanger-pathogens/snp_sites#39]
Maybe this is a dumb question, but I'm having a hard time installing this on my school's linux box. They are running redhat, and I am not sure if it is exactly compatible. The configure command for starters doesn't seem to work. I was looking into converting the package but it looks like it requires another program that requires root access, which I do not have.

**Comment by andrewjpage** [comment]
If the configure command doesnt work (after running 'autoreconf -i -f'), then its probable that the standard development tools are not installed/available. You probably wont be able to do much without talking to your Linux system administrator. I can confirm that snp_sites does work on redhat.
