### ISSUE TITLE
specify reference sequence

### ISSUE THREAD

**Issue by biorelated** [sanger-pathogens/snp_sites#44]
How can someone specify that a given sequence is the reference and comparisons should be relative to the given sequence? Does the tool assume that the first sequence in the alignment is the reference sequence?

**Comment by tseemann** [comment]
Yes, the first sequence in the multi FASTA is assumed to be the "reference". I don't think it matters which sequence is the "reference" as you should get the same result output file even if you re-order the sequences. But maybe @andrewjpage can confirm that!

**Comment by andrewjpage** [comment]
The software generates its own internal reference.  The 'reference' can be assumed to be the first sequence, however this is only of interest if you are using the VCF output, where it populates the REF column. For all other outputs the order of the sequences doesnt make any difference.   If there is missing data in the first sequence, it looks to the next sequence to try and populate those bases.
