### ISSUE TITLE
Build is failing on Mac OS

### ISSUE THREAD

**Issue by bouzidnm** [sanger-pathogens/snp_sites#45]
Required user to install automake, autoconf, libtool, and check.

Fails to build from the github download with the following error:

`./configure: line 3030: syntax error near unexpected token `CHECK,check'    
./configure: line 3030: `PKG_CHECK_MODULES(CHECK,check >= 0.8.2,have_check="yes",'`

**Comment by bouzidnm** [comment]
I copied the contents of m4 into the main directory and it built successfully. Problem solved.

**Comment by andrewjpage** [comment]
Excellent thanks for letting me know

**Comment by johannanvs** [comment]
For what it's worth, copying the m4 into main and making sure automake, autoconf, libtool, and check were installed did not do the trick for me. Installing pkgconfig as well, however, did make that error message disappear.
